### PR TITLE
Adding MACOS failure because of BSD grep

### LINKED ISSUE #8: It will break in MACOS because grep by default is BSD not GNU in MACOS
./fbid.sh 

		  _         ___  _  
		 |_ |_  | |  |  | \ 
		 |  |_) |_| _|_ |_/ 
					                    

 
   -Extract UserIDs From Public Facebook Accounts-
      
---Made With Love By - Baibhav | Twitter : @spongebhav---

Enter Username: zuck

usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Facebook is probably blocking our request. Please try again later.

We can add check for this in code.

### PR DESCRIPTION
**Pull request by prayas1337**
Added if statment to check if grep is BSD if yes then running different regex to grep fbid.

### CODE REVIEW

**Comment by baibhavanand** [comment]
Hi the regex you provided would also work on GNU, 
wouldn't it be better if instead of if__else we directly change the regex to the one you provided which won't break in BSD.

If you think the same feel free to make an additional commit by removing the if__else and directly changing the regex, if you have any additional doubt do let me know.

**Comment by prayas1337** [comment]
Hello @baibhavanand ,

You are correct the new regex should work regardless grep version but I did not want to change you logic code so I thought of adding my lines in if statement to handle case where grep is BSD instead GNU. Grep -o -P should work much faster than mine. But if you like I can make another commit with single regex without if else. Let me know your final thoughts , thanks for your time.

Thanks
-Prayas

**Comment by baibhavanand** [comment]
hi @prayas1337 

did the code work in your mac?

I provided the updated code to a friend and it also seems to give the same error

**Comment by prayas1337** [comment]
Hello @baibhavanand 

Yes the new code is working fine as expected i tested on Mac and Linux 

Mac:

```
$ ./fb.sh 

		  _         ___  _  
		 |_ |_  | |  |  | \ 
		 |  |_) |_| _|_ |_/ 
					                    

 
   -Extract UserIDs From Public Facebook Accounts-
      
---Made With Love By - Baibhav | Twitter : @spongebhav---


Enter Username: zuck


The UserID for zuck is: 4 

$ uname -a
Darwin  19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

**Comment by baibhavanand** [comment]
Merging this pull request. Thank you so much for your contribution.

**Pull request merged**
