### PR TITLE
Add modules to get uid and render result

### PR DESCRIPTION
**Pull request by sajxraj**
In this PR, I have done following changes:

- [x] Add a reusable function to fetch user id from Facebook
- [x] Add a reusable function to render result 
- [x] Fixed typo in doc
- [x] Replace move command by copy command and it can be useful for future if the installed file is lost

### CODE REVIEW

**Comment by baibhavanand** [comment]
Hi Sajan,
Thanks for the PR.
The code changes you did in fbuid makes the -u (-u works but repeats the result.) and -f argument non-functioning. Can you please correct it?
I really appreciate you changing the mv to cp.

**Comment by sazanrjb** [comment]
> Hi Sajan,
> Thanks for the PR.
> The code changes you did in fbuid makes the -u (-u works but repeats the result.) and -f argument non-functioning. Can you please correct it?
> I really appreciate you changing the mv to cp.

@baibhavanand Isn't it working? I checked multiple times and it was working fine. Any specific way to replicate?
image

**Comment by sajxraj** [comment]
> Hi Sajan,
> Thanks for the PR.
> The code changes you did in fbuid makes the -u (-u works but repeats the result.) and -f argument non-functioning. Can you please correct it?
> I really appreciate you changing the mv to cp.

@baibhavanand Isn't it working? I checked multiple times and it was working fine. Any specific way to replicate?
image

**Review by baibhavanand — APPROVED** [review]
I am so sorry.
It was a mistake on my end. I combined both the deleted and added codes.
I rechecked. Works like charm.
Thanks for your contribution.

**Pull request merged**
